### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Musgood** [Vaei/PredictedMovementExample#1]
Hi! I added the plugin to plugin folder, generated VS files, compile with several errors
Can you please look into it ?

**Comment by Vaei** [comment]
1. What engine version are you using?
2. What are the errors?
3. Did you follow the instructions for cloning?

**Comment by Musgood** [comment]
5.1.1, VS2022, Win 10.0.19041
I didnt clone just downloaded a zip file, but i dont get how it can be the issue.
Compile errors only in PredictedExampleCharacterMovement class:

Build started...
1>------ Build started: Project: PredictedExample, Configuration: Development_Editor x64 ------
1>Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" PredictedExampleEditor Win64 Development -Project="C:\PredictedMovementExample\PredictedExample.uproject" -WaitMutex -FromMsBuild
1>Log file: C:\Users\Musgood\AppData\Local\UnrealBuildTool\Log.txt
1>Creating makefile for PredictedExampleEditor (no existing makefile)
1>Parsing headers for PredictedExampleEditor
1>  Running Internal UnrealHeaderTool C:\PredictedMovementExample\PredictedExample.uproject C:\PredictedMovementExample\Intermediate\Build\Win64\PredictedExampleEditor\Development\PredictedExampleEditor.uhtmanifest -WarningsAsErrors -installed
1>Total of 24 written
1>Reflection code generated for PredictedExampleEditor in 1.8590066 seconds
1>Building PredictedExampleEditor...
1>Using Visual Studio 2022 14.35.32217 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Determining max actions to execute in parallel (4 physical cores, 4 logical cores)
1>  Executing up to 4 processes, one per physical core
1>Building 17 actions with 4 processes...
1>[1/17] Resource Default.rc2
1>[2/17] Resource Default.rc2
1>[3/17] Compile SharedPCH.Engine.ShadowErrors.cpp
1>[4/17] Compile PredictedExampleCharacterMovement.gen.cpp
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.h(60): error C3668: 'UPredictedExampleCharacterMovement::CanProneInCurrentState': method with override specifier 'override' did not override any base class methods
1>[5/17] Compile PredictedExample.cpp
1>[6/17] Compile PredictedExampleGameMode.gen.cpp
1>[7/17] Compile PredictedExampleCharacter.gen.cpp
1>[8/17] Compile PredictedExample.init.gen.cpp
1>[9/17] Compile Module.PredictedMovement.cpp
1>[10/17] Link UnrealEditor-PredictedMovement.lib
1>   Creating library C:\PredictedMovementExample\Plugins\PredictedMovement\Intermediate\Build\Win64\UnrealEditor\Development\PredictedMovement\UnrealEditor-PredictedMovement.lib and object C:\PredictedMovementExample\Plugins\PredictedMovement\Intermediate\Build\Win64\UnrealEditor\Development\PredictedMovement\UnrealEditor-PredictedMovement.exp
1>[11/17] Compile PredictedExampleGameMode.cpp
1>[12/17] Compile PredictedExampleCharacterMovement.cpp
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.h(60): error C3668: 'UPredictedExampleCharacterMovement::CanProneInCurrentState': method with override specifier 'override' did not override any base class methods
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.cpp(17): error C2065: 'MaxAccelerationSprinting': undeclared identifier
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.cpp(18): error C2065: 'MaxWalkSpeedSprinting': undeclared identifier
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.cpp(119): error C3861: 'UnSprint': identifier not found
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.cpp(163): error C3861: 'IsSprintingAtSpeed': identifier not found
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.cpp(216): error C2039: 'CanProneInCurrentState': is not a member of 'UStaminaMovement'
1>C:\PredictedMovementExample\Plugins\PredictedMovement\Source\PredictedMovement\Public\Stamina\StaminaMovement.h(53): note: see declaration of 'UStaminaMovement'
1>[13/17] Link UnrealEditor-PredictedMovement.dll
1>   Creating library C:\PredictedMovementExample\Plugins\PredictedMovement\Intermediate\Build\Win64\UnrealEditor\Development\PredictedMovement\UnrealEditor-PredictedMovement.suppressed.lib and object C:\PredictedMovementExample\Plugins\PredictedMovement\Intermediate\Build\Win64\UnrealEditor\Development\PredictedMovement\UnrealEditor-PredictedMovement.suppressed.exp
1>[14/17] Compile PredictedExampleCharacter.cpp
1>C:\PredictedMovementExample\Source\PredictedExample\PredictedExampleCharacterMovement.h(60): error C3668: 'UPredictedExampleCharacterMovement::CanProneInCurrentState': method with override specifier 'override' did not override any base class methods
1>[15/17] Link UnrealEditor-PredictedExample.dll cancelled
1>[16/17] Link UnrealEditor-PredictedExample.lib cancelled
1>[17/17] WriteMetadata PredictedExampleEditor.target cancelled
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command ""C:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat" PredictedExampleEditor Win64 Development -Project="C:\PredictedMovementExample\PredictedExample.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "PredictedExample.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Vaei** [comment]
It is failing to find methods from the plugin's parent classes. Please follow the instructions in the readme. This project uses the plugin as a submodule, zipping will not grab the submodule.

**Comment by Musgood** [comment]
Both plugin and Example needs to be cloned ?

**Comment by Vaei** [comment]
No. Follow the instructions in the ReadMe. The information is all already
there. It's a few lines.

**Comment by Musgood** [comment]
Thank you! All compiled
