### ISSUE TITLE
Compiling errors with link branch

### ISSUE THREAD

**Issue by Musgood** [Vaei/PredictedMovementExample#5]
Hi! Can you update this example? There is compile errors in PredictedExampleCharacterMovement and character BP

**Comment by Vaei** [comment]
No compile errors occurred in 5.1, 5.2, or 5.3, with PredictedMovement 1.0.1.2 or 1.0.2.3. Closing as this cannot be reproduced. If you believe there is an issue with PredictedMovement or PredictedMovementExample then include the compile errors and reproduction steps.
